services:
  db:
    container_name: factorial
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=factorial'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=indicasta'
    ports:
      - '5432:5432'
    restart: unless-stopped

  factorial-react:
    container_name: factorial-react
    image: factorial/factorial-react
    build:
      context: frontend/react
      args:
        api_base_url: http://localhost:8088
    ports:
      - "3000:5432"
    depends_on:
      - db
    restart: unless-stopped
volumes:
  db:
